name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: esp-idf Toolchain Setup
      run: |
        sudo apt-get install git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        mkdir -p ~/esp
        cd ~/esp
        git clone -b v4.4.2 --recursive https://github.com/espressif/esp-idf.git
        cd ~/esp/esp-idf
        ./install.sh esp32c3
        . ~/esp/esp-idf/export.sh
        pip3 install -r $IDF_PATH/requirements.txt
    - name: Build
      run: |
        . ~/esp/esp-idf/export.sh
        idf.py build
        cd wasm
        npm install
        npm run asbuild
